# Be sure to restart your server when you modify this file

# Specifies gem version of Rails to use when vendor/rails is not present
RAILS_GEM_VERSION = '2.3.5' unless defined? RAILS_GEM_VERSION

# Bootstrap the Rails environment, frameworks, and default configuration
require File.join(File.dirname(__FILE__), 'boot')

require 'matching_users_paginator'
require 'geosearch'
require 'emailnotification'
require 'validates_creation_count'
require 'validates_blankness_of'
require 'in_last_24_hours_extension'

Rails::Initializer.run do |config|
  # Settings in config/environments/* take precedence over those specified here.
  # Application configuration should go into files in config/initializers
  # -- all .rb files in that directory are automatically loaded.

  # Add additional load paths for your own custom dirs
  # config.load_paths += %W( #{RAILS_ROOT}/extras )
  config.load_paths += %W( #{RAILS_ROOT}/app/sweepers )

  # Specify gems that this application depends on and have them installed with rake gems:install
  config.gem "geokit"
  config.gem "twitter"
  config.gem "rspec", :lib => "spec"
  config.gem 'twitter-auth', :lib => 'twitter_auth'
  config.gem "thoughtbot-factory_girl", :lib => "factory_girl", :source => "http://gems.github.com"
  config.gem "faker"
  config.gem "mysql"
  config.gem 'freelancing-god-thinking-sphinx',:lib => 'thinking_sphinx', :source => 'http://gems.github.com'
  config.gem "paperclip"
  config.gem "email_spec"
  config.gem "awesome_print", :lib => "ap"
  config.gem 'mislav-will_paginate', :version => '~> 2.3.11', :lib => 'will_paginate', 
      :source => 'http://gems.github.com'
  config.gem "fakeweb"
  # The line below raises a "no such file to load -- json" when running
  # "sudo rake gems:install". Urgh. (Brad Bollenbach, 2009-09-15)
  config.gem "json"
  config.gem "ambethia-smtp-tls", :lib => "smtp-tls", :source => "http://gems.github.com/"
  # For some reason, if I UNcomment the line below, rake db:load:fixtures
  # insists on loading fixtures into the test db, rather than dev.
  # (Brad Bollenbach, 2009-09-15)
  # config.gem "rspec-rails", :lib => "spec/rails"


  # Only load the plugins named here, in the order given (default is alphabetical).
  # :all can be used as a placeholder for all plugins not explicitly named
  # config.plugins = [ :exception_notification, :ssl_requirement, :all ]

  # Skip frameworks you're not going to use. To use Rails without a database,
  # you must remove the Active Record framework.
  # config.frameworks -= [ :active_record, :active_resource, :action_mailer ]

  # Activate observers that should always be running
  #config.active_record.observers = :user_sweeper

  # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
  # Run "rake -D time" for a list of tasks for finding time zone names.
  config.time_zone = 'UTC'

  # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
  # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}')]
  # config.i18n.default_locale = :de
  
  # Leave this at 100, because our Twitter queries (e.g. for friends and followers lists)
  # return 100 users per page, so for consistency all listings should show 100 users.
  DEFAULT_SEARCH_RESULTS_PER_PAGE = 100
end

module Constants
  POT_BOT_ID = 83433496
  POT_HUMAN_ID = 72211560

  STATES = {
    'AL'=>'Alabama',
    'AK'=>'Alaska',
    'AZ'=>'Arizona',
    'AR'=>'Arkansas',
    'CA'=>'California',
    'CO'=>'Colorado',
    'CT'=>'Connecticut',
    'DE'=>'Delaware',
    'DC'=>'District of Columbia',
    'FL'=>'Florida',
    'GA'=>'Georgia',
    'GU'=>'Guam',
    'HI'=>'Hawaii',
    'ID'=>'Idaho',
    'IL'=>'Illinois',
    'IN'=>'Indiana',
    'IA'=>'Iowa',
    'KS'=>'Kansas',
    'KY'=>'Kentucky',
    'LA'=>'Louisiana',
    'ME'=>'Maine',
    'MD'=>'Maryland',
    'MA'=>'Massachusetts',
    'MI'=>'Michigan',
    'MN'=>'Minnesota',
    'MS'=>'Mississippi',
    'MO'=>'Missouri',
    'MT'=>'Montana',
    'NE'=>'Nebraska',
    'NV'=>'Nevada',
    'NH'=>'New Hampshire',
    'NJ'=>'New Jersey',
    'NM'=>'New Mexico',
    'NY'=>'New York',
    'NC'=>'North Carolina',
    'ND'=>'North Dakota',
    'OH'=>'Ohio',
    'OK'=>'Oklahoma',
    'OR'=>'Oregon',
    'PA'=>'Pennsylvania',
    'PR'=>'Puerto Rico',
    'RI'=>'Rhode Island',
    'SC'=>'South Carolina',
    'SD'=>'South Dakota',
    'TN'=>'Tennessee',
    'TX'=>'Texas',
    'UT'=>'Utah',
    'VT'=>'Vermont',
    'VI'=>'Virgin Island',
    'VA'=>'Virginia',
    'WA'=>'Washington',
    'WV'=>'West Virginia',
    'WI'=>'Wisconsin',
    'WY'=>'Wyoming'
  }

  COUNTRIES = {
    'AD'=>'Andorra',
    'AE'=>'United Arab Emirates',
    'AF'=>'Afghanistan',
    'AG'=>'Antigua and Barbuda',
    'AI'=>'Anguilla',
    'AL'=>'Albania',
    'AM'=>'Armenia',
    'AN'=>'Netherlands Antilles',
    'AO'=>'Angola',
    'AQ'=>'Antarctica',
    'AR'=>'Argentina',
    'AS'=>'American Samoa',
    'AT'=>'Austria',
    'AU'=>'Australia',
    'AW'=>'Aruba',
    'AX'=>'Aland Islands',
    'AZ'=>'Azerbaijan',
    'BA'=>'Bosnia and Herzegovina',
    'BB'=>'Barbados',
    'BD'=>'Bangladesh',
    'BE'=>'Belgium',
    'BF'=>'Burkina Faso',
    'BG'=>'Bulgaria',
    'BH'=>'Bahrain',
    'BI'=>'Burundi',
    'BJ'=>'Benin',
    'BM'=>'Bermuda',
    'BN'=>'Brunei Darussalam',
    'BO'=>'Bolivia',
    'BR'=>'Brazil',
    'BS'=>'Bahamas',
    'BT'=>'Bhutan',
    'BV'=>'Bouvet Island',
    'BW'=>'Botswana',
    'BY'=>'Belarus',
    'BZ'=>'Belize',
    'CA'=>'Canada',
    'CC'=>'Cocos (Keeling) Islands',
    'CD'=>'Democratic Rep. of Congo',
    'CF'=>'Central African Republic',
    'CG'=>'Congo',
    'CH'=>'Switzerland',
    'CI'=>'Cote D\'Ivoire',
    'CK'=>'Cook Islands',
    'CL'=>'Chile',
    'CM'=>'Cameroon',
    'CN'=>'China',
    'CO'=>'Colombia',
    'CR'=>'Costa Rica',
    'CS'=>'Serbia and Montenegro',
    'CU'=>'Cuba',
    'CV'=>'Cape Verde',
    'CX'=>'Christmas Island',
    'CY'=>'Cyprus',
    'CZ'=>'Czech Republic',
    'DE'=>'Germany',
    'DJ'=>'Djibouti',
    'DK'=>'Denmark',
    'DM'=>'Dominica',
    'DO'=>'Dominican Republic',
    'DZ'=>'Algeria',
    'EC'=>'Ecuador',
    'EE'=>'Estonia',
    'EG'=>'Egypt',
    'EH'=>'Western Sahara',
    'ER'=>'Eritrea',
    'ES'=>'Spain',
    'ET'=>'Ethiopia',
    'FI'=>'Finland',
    'FJ'=>'Fiji',
    'FK'=>'Falkland Islands',
    'FM'=>'Micronesia',
    'FO'=>'Faroe Islands',
    'FR'=>'France',
    'FX'=>'France, Metropolitan',
    'GA'=>'Gabon',
    'GB'=>'UK',
    'GD'=>'Grenada',
    'GE'=>'Georgia',
    'GF'=>'French Guiana',
    'GH'=>'Ghana',
    'GI'=>'Gibraltar',
    'GL'=>'Greenland',
    'GM'=>'Gambia',
    'GN'=>'Guinea',
    'GP'=>'Guadeloupe',
    'GQ'=>'Equatorial Guinea',
    'GR'=>'Greece',
    'GS'=>'S. Sandwich Islands',
    'GT'=>'Guatemala',
    'GU'=>'Guam',
    'GW'=>'Guinea-Bissau',
    'GY'=>'Guyana',
    'HK'=>'Hong Kong',
    'HM'=>'Heard Island',
    'HN'=>'Honduras',
    'HR'=>'Croatia (Hrvatska)',
    'HT'=>'Haiti',
    'HU'=>'Hungary',
    'ID'=>'Indonesia',
    'IE'=>'Ireland',
    'IL'=>'Israel',
    'IN'=>'India',
    'IO'=>'British Indian Ocean',
    'IQ'=>'Iraq',
    'IR'=>'Iran',
    'IS'=>'Iceland',
    'IT'=>'Italy',
    'JM'=>'Jamaica',
    'JO'=>'Jordan',
    'JP'=>'Japan',
    'KE'=>'Kenya',
    'KG'=>'Kyrgyzstan',
    'KH'=>'Cambodia',
    'KI'=>'Kiribati',
    'KM'=>'Comoros',
    'KN'=>'Saint Kitts and Nevis',
    'KP'=>'Korea (North)',
    'KR'=>'Korea (South)',
    'KW'=>'Kuwait',
    'KY'=>'Cayman Islands',
    'KZ'=>'Kazakhstan',
    'LA'=>'Laos',
    'LB'=>'Lebanon',
    'LC'=>'Saint Lucia',
    'LI'=>'Liechtenstein',
    'LK'=>'Sri Lanka',
    'LR'=>'Liberia',
    'LS'=>'Lesotho',
    'LT'=>'Lithuania',
    'LU'=>'Luxembourg',
    'LV'=>'Latvia',
    'LY'=>'Libya',
    'MA'=>'Morocco',
    'MC'=>'Monaco',
    'MD'=>'Moldova',
    'MG'=>'Madagascar',
    'MH'=>'Marshall Islands',
    'MK'=>'Macedonia',
    'ML'=>'Mali',
    'MM'=>'Myanmar',
    'MN'=>'Mongolia',
    'MO'=>'Macao',
    'MP'=>'Northern Mariana Islands',
    'MQ'=>'Martinique',
    'MR'=>'Mauritania',
    'MS'=>'Montserrat',
    'MT'=>'Malta',
    'MU'=>'Mauritius',
    'MV'=>'Maldives',
    'MW'=>'Malawi',
    'MX'=>'Mexico',
    'MY'=>'Malaysia',
    'MZ'=>'Mozambique',
    'NA'=>'Namibia',
    'NC'=>'New Caledonia',
    'NE'=>'Niger',
    'NF'=>'Norfolk Island',
    'NG'=>'Nigeria',
    'NI'=>'Nicaragua',
    'NL'=>'Netherlands',
    'NO'=>'Norway',
    'NP'=>'Nepal',
    'NR'=>'Nauru',
    'NU'=>'Niue',
    'NZ'=>'New Zealand',
    'OM'=>'Oman',
    'PA'=>'Panama',
    'PE'=>'Peru',
    'PF'=>'French Polynesia',
    'PG'=>'Papua New Guinea',
    'PH'=>'Philippines',
    'PK'=>'Pakistan',
    'PL'=>'Poland',
    'PM'=>'Saint Pierre',
    'PN'=>'Pitcairn',
    'PR'=>'Puerto Rico',
    'PS'=>'Palestinian Territory',
    'PT'=>'Portugal',
    'PW'=>'Palau',
    'PY'=>'Paraguay',
    'QA'=>'Qatar',
    'RE'=>'Reunion',
    'RO'=>'Romania',
    'RU'=>'Russian Federation',
    'RW'=>'Rwanda',
    'SA'=>'Saudi Arabia',
    'SB'=>'Solomon Islands',
    'SC'=>'Seychelles',
    'SD'=>'Sudan',
    'SE'=>'Sweden',
    'SG'=>'Singapore',
    'SH'=>'Saint Helena',
    'SI'=>'Slovenia',
    'SJ'=>'Svalbard and Jan Mayen',
    'SK'=>'Slovakia',
    'SL'=>'Sierra Leone',
    'SM'=>'San Marino',
    'SN'=>'Senegal',
    'SO'=>'Somalia',
    'SR'=>'Suriname',
    'ST'=>'Sao Tome and Principe',
    'SU'=>'USSR (former)',
    'SV'=>'El Salvador',
    'SY'=>'Syria',
    'SZ'=>'Swaziland',
    'TC'=>'Turks and Caicos Islands',
    'TD'=>'Chad',
    'TF'=>'French Southern Territories',
    'TG'=>'Togo',
    'TH'=>'Thailand',
    'TJ'=>'Tajikistan',
    'TK'=>'Tokelau',
    'TL'=>'Timor-Leste',
    'TM'=>'Turkmenistan',
    'TN'=>'Tunisia',
    'TO'=>'Tonga',
    'TP'=>'East Timor',
    'TR'=>'Turkey',
    'TT'=>'Trinidad and Tobago',
    'TV'=>'Tuvalu',
    'TW'=>'Taiwan',
    'TZ'=>'Tanzania',
    'UA'=>'Ukraine',
    'UG'=>'Uganda',
    'UK'=>'United Kingdom',
    'UM'=>'US Outlying Islands',
    'US'=>'USA',
    'UY'=>'Uruguay',
    'UZ'=>'Uzbekistan',
    'VA'=>'Vatican City State',
    'VC'=>'Saint Vincent',
    'VE'=>'Venezuela',
    'VG'=>'Virgin Islands (UK)',
    'VI'=>'Virgin Islands (US)',
    'VN'=>'Viet Nam',
    'VU'=>'Vanuatu',
    'WF'=>'Wallis and Futuna',
    'WS'=>'Samoa',
    'YE'=>'Yemen',
    'YT'=>'Mayotte',
    'YU'=>'Yugoslavia (former)',
    'ZA'=>'South Africa',
    'ZM'=>'Zambia',
    'ZR'=>'Zaire (former)',
    'ZW'=>'Zimbabwe'
  }
  
  US_CITIES = [
    "new york",
    "los angeles",
    "chicago",
    "houston",
    "phoenix",
    "philadelphia",
    "san antonio",
    "dallas",
    "san diego",
    "san jose",
    "detroit",
    "san francisco",
    "jacksonville",
    "indianapolis",
    "austin",
    "columbus",
    "fort worth",
    "charlotte",
    "memphis",
    "baltimore",
    "el paso",
    "boston",
    "milwaukee",
    "denver",
    "seattle",
    "nashville",
    "washington",
    "las vegas",
    "portland",
    "louisville",
    "oklahoma city",
    "tucson",
    "atlanta",
    "albuquerque",
    "fresno",
    "sacramento",
    "long beach",
    "mesa",
    "kansas city",
    "omaha",
    "cleveland",
    "virginia beach",
    "miami",
    "oakland",
    "raleigh",
    "tulsa",
    "minneapolis",
    "colorado springs",
    "honolulu",
    "arlington"
  ]
    
  CANADIAN_CITIES = [
    "toronto",
    "montreal",
    "vancouver",
    "ottawa",
    "calgary",
    "edmonton",
    "quebec city",
    "winnipeg",
    "hamilton",
    "london",
    "kitchener",
    "st catharines-niagara",
    "halifax",
    "oshawa",
    "victoria",
    "windsor",
    "saskatoon",
    "regina",
    "sherbrooke",
    "st. john's"
  ]
  
  EUROPEAN_CITIES = [
    ["london", "uk"],
    ["berlin", "de"],
    ["madrid", "sp"],
    ["rome", "it"],
    ["paris", "fr"],
    ["bucharest", "ro"],
    ["hamburg", "de"],
    ["budapest", "hu"],
    ["warsaw", "po"],
    ["vienna", "at"],
    ["barcelona", "es"],
    ["milan", "it"],
    ["munich", "de"],
    ["prague", "uk"],
    ["sofia", "bg"],
    ["brussels", "be"],
    ["birmingham", "uk"],
    ["cologne", "de"],
    ["marseille", "fr"],
    ["athens", "gr"],
    ["valencia", "es"],
    ["stockholm", "se"],
    ["amsterdam", "nl"],
    ["riga", "lv"],
    ["leeds", "uk"],
    ["frankfurt", "de"],
    ["rotterdam", "nl"],
    ["stuttgart", "de"],
    ["dortmund", "de"],
    ["glasgow", "uk"],
    ["helsinki", "fi"],
    ["vilnius", "lt"],
    ["lisbon", "pt"],
    ["sheffield", "uk"],
    ["copenhagen", "dk"],
    ["gothenburg", "se"],
    ["dublin", "ie"]
  ]
end

INTROVERT = AccountType.new :daily_smile_limit        => 1,
                            :daily_message_limit      => 1,
                            :daily_like_profile_limit => 1,
                            :photo_upload_limit       => 2,
                            :account_type             => "I",
                            :display_name             => "Basic" 

CONNECTOR = AccountType.new :daily_smile_limit                    => 5,
                            :daily_message_limit                  => 5,
                            :daily_like_profile_limit             => 5,
                            :photo_upload_limit                   => 4,
                            :can_see_site_wide_image_gallery      => true,
                            :can_see_who_has_viewed_their_profile => true, 
                            :can_see_sent_messages_read           => true, 
                            :account_type                         => "C",
                            :display_name                         => "Plus",
                            :price                                => 19.95

SOCIAL_SKYDIVER = AccountType.new :daily_smile_limit                    => 12,
                                  :daily_message_limit                  => 12,
                                  :daily_like_profile_limit             => 12,
                                  :photo_upload_limit                   => 10,
                                  :can_see_site_wide_image_gallery      => true,
                                  :can_see_who_has_viewed_their_profile => true,
                                  :can_see_sent_messages_read           => true, 
                                  :candidate_for_premium_ads            => true,
                                  :account_type                         => "S",
                                  :display_name                         => "Premium",
                                  :price                                => 29.95
